# **Cafe DataSet** #

## **1. Data Understanding (Data Description)** ##

In [68]:
# import library
import pandas as pd
import numpy as np

In [69]:
# import kaggle enviroment and download dataset
!pip install opendatasets
import opendatasets as od

Requirement already satisfied: opendatasets in d:\anaconda\lib\site-packages (0.1.22)
Requirement already satisfied: tqdm in d:\anaconda\lib\site-packages (from opendatasets) (4.66.5)
Requirement already satisfied: kaggle in d:\anaconda\lib\site-packages (from opendatasets) (1.7.4.5)
Requirement already satisfied: click in d:\anaconda\lib\site-packages (from opendatasets) (8.1.7)
Requirement already satisfied: colorama in d:\anaconda\lib\site-packages (from click->opendatasets) (0.4.6)
Requirement already satisfied: bleach in d:\anaconda\lib\site-packages (from kaggle->opendatasets) (4.1.0)
Requirement already satisfied: certifi>=14.05.14 in d:\anaconda\lib\site-packages (from kaggle->opendatasets) (2025.6.15)
Requirement already satisfied: charset-normalizer in d:\anaconda\lib\site-packages (from kaggle->opendatasets) (3.3.2)
Requirement already satisfied: idna in d:\anaconda\lib\site-packages (from kaggle->opendatasets) (3.7)
Requirement already satisfied: protobuf in d:\anaconda\lib\site-packages (from kaggle->opendatasets) (4.25.3)
Requirement already satisfied: python-dateutil>=2.5.3 in d:\anaconda\lib\site-packages (from kaggle->opendatasets) (2.9.0.post0)
Requirement already satisfied: python-slugify in d:\anaconda\lib\site-packages (from kaggle->opendatasets) (5.0.2)
Requirement already satisfied: requests in d:\anaconda\lib\site-packages (from kaggle->opendatasets) (2.32.3)
Requirement already satisfied: setuptools>=21.0.0 in d:\anaconda\lib\site-packages (from kaggle->opendatasets) (75.1.0)
Requirement already satisfied: six>=1.10 in d:\anaconda\lib\site-packages (from kaggle->opendatasets) (1.16.0)
Requirement already satisfied: text-unidecode in d:\anaconda\lib\site-packages (from kaggle->opendatasets) (1.3)
Requirement already satisfied: urllib3>=1.15.1 in d:\anaconda\lib\site-packages (from kaggle->opendatasets) (2.2.3)
Requirement already satisfied: webencodings in d:\anaconda\lib\site-packages (from kaggle->opendatasets) (0.5.1)
Requirement already satisfied: packaging in d:\anaconda\lib\site-packages (from bleach->kaggle->opendatasets) (24.1)

In [70]:
od.download("https://www.kaggle.com/datasets/ahmedmohamed2003/cafe-sales-dirty-data-for-cleaning-training")

Skipping, found downloaded files in ".\cafe-sales-dirty-data-for-cleaning-training" (use force=True to force download)

In [71]:
import os
os.listdir()

['.ipynb_checkpoints',
 'Business Analysis by SQL.sql',
 'Business Problem Statement.docx',
 'Cafe Sales Dashboard.pbix',
 'cafe-sales-dirty-data-for-cleaning-training',
 'CafeData.ipynb',
 'Cafe_sales_schema.sql',
 'Cleaned_cafeData.csv']

In [72]:
# read the data
df = pd.read_csv("C:\\Users\\limyo\\Documents\\Cafe Sales Analysis\\cafe-sales-dirty-data-for-cleaning-training\\dirty_cafe_sales.csv")
df

,Transaction ID,Item,Quantity,Price Per Unit,Total Spent,Payment Method,Location,Transaction Date
0,TXN_1961373,Coffee,2,2.0,4.0,Credit Card,Takeaway,2023-09-08
1,TXN_4977031,Cake,4,3.0,12.0,Cash,In-store,2023-05-16
2,TXN_4271903,Cookie,4,1.0,ERROR,Credit Card,In-store,2023-07-19
3,TXN_7034554,Salad,2,5.0,10.0,UNKNOWN,UNKNOWN,2023-04-27
4,TXN_3160411,Coffee,2,2.0,4.0,Digital Wallet,In-store,2023-06-11
...,...,...,...,...,...,...,...,...
9995,TXN_7672686,Coffee,2,2.0,4.0,NaN,UNKNOWN,2023-08-30
9996,TXN_9659401,NaN,3,NaN,3.0,Digital Wallet,NaN,2023-06-02
9997,TXN_5255387,Coffee,4,2.0,8.0,Digital Wallet,NaN,2023-03-02
9998,TXN_7695629,Cookie,3,NaN,3.0,Digital Wallet,NaN,2023-12-02
9999,TXN_6170729,Sandwich,3,4.0,12.0,Cash,In-store,2023-11-07

In [73]:
# Check data size
df.shape

(10000, 8)

In [74]:
# show first 5 rows data
df.head()

,Transaction ID,Item,Quantity,Price Per Unit,Total Spent,Payment Method,Location,Transaction Date
0,TXN_1961373,Coffee,2,2.0,4.0,Credit Card,Takeaway,2023-09-08
1,TXN_4977031,Cake,4,3.0,12.0,Cash,In-store,2023-05-16
2,TXN_4271903,Cookie,4,1.0,ERROR,Credit Card,In-store,2023-07-19
3,TXN_7034554,Salad,2,5.0,10.0,UNKNOWN,UNKNOWN,2023-04-27
4,TXN_3160411,Coffee,2,2.0,4.0,Digital Wallet,In-store,2023-06-11

In [75]:
# show last 5 rows data
df.tail()

,Transaction ID,Item,Quantity,Price Per Unit,Total Spent,Payment Method,Location,Transaction Date
9995,TXN_7672686,Coffee,2,2.0,4.0,NaN,UNKNOWN,2023-08-30
9996,TXN_9659401,NaN,3,NaN,3.0,Digital Wallet,NaN,2023-06-02
9997,TXN_5255387,Coffee,4,2.0,8.0,Digital Wallet,NaN,2023-03-02
9998,TXN_7695629,Cookie,3,NaN,3.0,Digital Wallet,NaN,2023-12-02
9999,TXN_6170729,Sandwich,3,4.0,12.0,Cash,In-store,2023-11-07

In [76]:
# Check data info
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 8 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Transaction ID    10000 non-null  object
 1   Item              9667 non-null   object
 2   Quantity          9862 non-null   object
 3   Price Per Unit    9821 non-null   object
 4   Total Spent       9827 non-null   object
 5   Payment Method    7421 non-null   object
 6   Location          6735 non-null   object
 7   Transaction Date  9841 non-null   object
dtypes: object(8)
memory usage: 625.1+ KB

In [77]:
# Check data statistical info
df.describe(include='all')

,Transaction ID,Item,Quantity,Price Per Unit,Total Spent,Payment Method,Location,Transaction Date
count,10000,9667,9862,9821,9827,7421,6735,9841
unique,10000,10,7,8,19,5,4,367
top,TXN_1961373,Juice,5,3.0,6.0,Digital Wallet,Takeaway,UNKNOWN
freq,1,1171,2013,2429,979,2291,3022,159

# **2. Data Preprocessing** #

Data Cleaning

In [80]:
# show all unique value for all column except Transaction ID and Transaction date
for col in df.columns:
  if col not in ['Transaction ID', 'Transaction Date']:
    print(f"{col}: {df[col].unique()}")

Item: ['Coffee' 'Cake' 'Cookie' 'Salad' 'Smoothie' 'UNKNOWN' 'Sandwich' nan
 'ERROR' 'Juice' 'Tea']
Quantity: ['2' '4' '5' '3' '1' 'ERROR' 'UNKNOWN' nan]
Price Per Unit: ['2.0' '3.0' '1.0' '5.0' '4.0' '1.5' nan 'ERROR' 'UNKNOWN']
Total Spent: ['4.0' '12.0' 'ERROR' '10.0' '20.0' '9.0' '16.0' '15.0' '25.0' '8.0' '5.0'
 '3.0' '6.0' nan 'UNKNOWN' '2.0' '1.0' '7.5' '4.5' '1.5']
Payment Method: ['Credit Card' 'Cash' 'UNKNOWN' 'Digital Wallet' 'ERROR' nan]
Location: ['Takeaway' 'In-store' 'UNKNOWN' nan 'ERROR']

In [81]:
# replace value "ERROR" AND "UNKNOWN" With null value for better data cleaning
df = df.replace(to_replace=["ERROR", "UNKNOWN"], value= pd.NA)

In [82]:
# Change data type

df['Item'] = df['Item'].astype('category')

df['Quantity'] = pd.to_numeric(df['Quantity'], errors='coerce').astype('Int64')

df['Price Per Unit'] = pd.to_numeric(df['Price Per Unit'], errors='coerce')
df['Total Spent'] = pd.to_numeric(df['Total Spent'], errors='coerce')
df['Payment Method'] = df['Payment Method'].astype('category')
df['Location'] = df['Location'].astype('category')
df['Transaction Date'] = pd.to_datetime(df['Transaction Date'], dayfirst=True, format='mixed',errors='coerce')

print(df.info())
df.describe(include="all")

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 8 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Transaction ID    10000 non-null  object
 1   Item              9031 non-null   category
 2   Quantity          9521 non-null   Int64
 3   Price Per Unit    9467 non-null   float64
 4   Total Spent       9498 non-null   float64
 5   Payment Method    6822 non-null   category
 6   Location          6039 non-null   category
 7   Transaction Date  9540 non-null   datetime64[ns]
dtypes: Int64(1), category(3), datetime64[ns](1), float64(2), object(1)
memory usage: 430.4+ KB
None

,Transaction ID,Item,Quantity,Price Per Unit,Total Spent,Payment Method,Location,Transaction Date
count,10000,9031,9521.0,9467.000000,9498.000000,6822,6039,9540
unique,10000,8,<NA>,NaN,NaN,3,2,NaN
top,TXN_1961373,Juice,<NA>,NaN,NaN,Digital Wallet,Takeaway,NaN
freq,1,1171,<NA>,NaN,NaN,2291,3022,NaN
mean,NaN,NaN,3.028463,2.949984,8.924352,NaN,NaN,2023-07-01 23:00:31.698113280
min,NaN,NaN,1.0,1.000000,1.000000,NaN,NaN,2023-01-01 00:00:00
25%,NaN,NaN,2.0,2.000000,4.000000,NaN,NaN,2023-04-01 00:00:00
50%,NaN,NaN,3.0,3.000000,8.000000,NaN,NaN,2023-07-02 00:00:00
75%,NaN,NaN,4.0,4.000000,12.000000,NaN,NaN,2023-10-02 00:00:00
max,NaN,NaN,5.0,5.000000,25.000000,NaN,NaN,2023-12-31 00:00:00
std,NaN,NaN,1.419007,1.278450,6.009919,NaN,NaN,NaN

In [83]:
# Check missing value
df.isnull().sum()

Transaction ID         0
Item                 969
Quantity             479
Price Per Unit       533
Total Spent          502
Payment Method      3178
Location            3961
Transaction Date     460
dtype: int64

In [84]:
# Fill/replace missing value
# Replace missing value by mode for each category column
df['Item'].fillna(df['Item'].mode()[0], inplace=True)
df['Payment Method'].fillna(df['Payment Method'].mode()[0], inplace=True)
df['Location'].fillna(df['Location'].mode()[0], inplace=True)

# fill in the price per unit based on the menu given 
df.loc[df['Item'] == 'Coffee', "Price Per Unit" ] = 2
df.loc[df['Item'] == 'Tea', "Price Per Unit" ] = 1.5
df.loc[df['Item'] == 'Sandwich', "Price Per Unit" ] = 4
df.loc[df['Item'] == 'Salad', "Price Per Unit" ] = 5
df.loc[df['Item'] == 'Cake', "Price Per Unit" ] = 3
df.loc[df['Item'] == 'Cookie', "Price Per Unit" ] = 1
df.loc[df['Item'] == 'Smoothie', "Price Per Unit" ] = 4
df.loc[df['Item'] == 'Juice', "Price Per Unit" ] = 3

print(df)
print(df.isna().sum())

     Transaction ID      Item  Quantity  Price Per Unit  Total Spent  \
0       TXN_1961373    Coffee         2             2.0          4.0
1       TXN_4977031      Cake         4             3.0         12.0
2       TXN_4271903    Cookie         4             1.0          NaN
3       TXN_7034554     Salad         2             5.0         10.0
4       TXN_3160411    Coffee         2             2.0          4.0
...             ...       ...       ...             ...          ...
9995    TXN_7672686    Coffee         2             2.0          4.0
9996    TXN_9659401     Juice         3             3.0          3.0
9997    TXN_5255387    Coffee         4             2.0          8.0
9998    TXN_7695629    Cookie         3             1.0          3.0
9999    TXN_6170729  Sandwich         3             4.0         12.0

      Payment Method  Location Transaction Date
0        Credit Card  Takeaway       2023-09-08
1               Cash  In-store       2023-05-16
2        Credit Card  In-store       2023-07-19
3     Digital Wallet  Takeaway       2023-04-27
4     Digital Wallet  In-store       2023-06-11
...              ...       ...              ...
9995  Digital Wallet  Takeaway       2023-08-30
9996  Digital Wallet  Takeaway       2023-06-02
9997  Digital Wallet  Takeaway       2023-03-02
9998  Digital Wallet  Takeaway       2023-12-02
9999            Cash  In-store       2023-11-07

[10000 rows x 8 columns]
Transaction ID        0
Item                  0
Quantity            479
Price Per Unit        0
Total Spent         502
Payment Method        0
Location              0
Transaction Date    460
dtype: int64

In [85]:
# Replace quantity with total spent divided by price per unit
df['Quantity'] = df['Quantity'].fillna((df['Total Spent'] / df['Price Per Unit']).round().astype('Int64'))

# Replace Total spent with Quantity times Price per unit
df['Total Spent'] = df['Total Spent'].fillna(df['Quantity'] * df['Price Per Unit'])

df.isna().sum()

Transaction ID        0
Item                  0
Quantity             20
Price Per Unit        0
Total Spent          20
Payment Method        0
Location              0
Transaction Date    460
dtype: int64

In [86]:
# chcek the column quantity and total spent that consists missing value
df[df['Quantity'].isna() | df['Total Spent'].isna()]

,Transaction ID,Item,Quantity,Price Per Unit,Total Spent,Payment Method,Location,Transaction Date
236,TXN_8562645,Salad,<NA>,5.0,<NA>,Digital Wallet,In-store,2023-05-18
278,TXN_3229409,Juice,<NA>,3.0,<NA>,Cash,Takeaway,2023-04-15
641,TXN_2962976,Juice,<NA>,3.0,<NA>,Digital Wallet,Takeaway,2023-03-17
738,TXN_8696094,Sandwich,<NA>,4.0,<NA>,Digital Wallet,Takeaway,2023-05-14
2796,TXN_9188692,Cake,<NA>,3.0,<NA>,Credit Card,Takeaway,2023-12-01
3203,TXN_4565754,Smoothie,<NA>,4.0,<NA>,Digital Wallet,Takeaway,2023-10-06
3224,TXN_6297232,Coffee,<NA>,2.0,<NA>,Digital Wallet,Takeaway,2023-04-07
3401,TXN_3251829,Tea,<NA>,1.5,<NA>,Digital Wallet,In-store,2023-07-25
4257,TXN_6470865,Coffee,<NA>,2.0,<NA>,Digital Wallet,Takeaway,2023-09-18
5841,TXN_5884081,Cookie,<NA>,1.0,<NA>,Digital Wallet,In-store,2023-07-05
7029,TXN_4628338,Coffee,<NA>,2.0,<NA>,Cash,Takeaway,2023-12-25
7297,TXN_9944500,Smoothie,<NA>,4.0,<NA>,Cash,In-store,2023-01-03
8021,TXN_2428781,Salad,<NA>,5.0,<NA>,Digital Wallet,In-store,2023-05-09
8443,TXN_2023651,Sandwich,<NA>,4.0,<NA>,Cash,In-store,2023-05-25
8465,TXN_9669616,Coffee,<NA>,2.0,<NA>,Digital Wallet,Takeaway,2023-06-03
8479,TXN_1547245,Sandwich,<NA>,4.0,<NA>,Digital Wallet,Takeaway,2023-09-11
8574,TXN_2546684,Juice,<NA>,3.0,<NA>,Digital Wallet,Takeaway,2023-04-08
8732,TXN_4550558,Cookie,<NA>,1.0,<NA>,Credit Card,In-store,2023-08-04
9590,TXN_9924732,Sandwich,<NA>,4.0,<NA>,Credit Card,In-store,2023-01-18
9869,TXN_1975184,Coffee,<NA>,2.0,<NA>,Digital Wallet,Takeaway,2023-01-15

In [87]:
# Check mean, median for quantity column and choose the suitable one to replace the missing value
Qtymean = df['Quantity'].mean()
Qtymedian = df['Quantity'].median()

print(Qtymean)
print(Qtymedian)

3.0244488977955912
3.0

In [88]:
# replace missing value in quantity column with median due to quantity column is int type data
df['Quantity'] = df['Quantity'].fillna(Qtymedian)

# fill na value again for the total spent column  (Quantity*Price Per Unit)
df['Total Spent'] = df['Total Spent'].fillna(df['Quantity'] * df['Price Per Unit'])

df.isna().sum()

Transaction ID        0
Item                  0
Quantity              0
Price Per Unit        0
Total Spent           0
Payment Method        0
Location              0
Transaction Date    460
dtype: int64

In [89]:
# check if the data is correct (Quantity * Price per unit  = total Spent)
df[df['Total Spent'] != (df['Quantity'] * df['Price Per Unit'])]

# correct the total spent with replace the true total spent
df.loc[df['Total Spent'] != (df['Quantity'] * df['Price Per Unit']), 'Total Spent'] = df['Quantity'] * df['Price Per Unit']

# recheck again the incorrect total spent
df[df['Total Spent'] != (df['Quantity'] * df['Price Per Unit'])]

Empty DataFrame
Columns: [Transaction ID, Item, Quantity, Price Per Unit, Total Spent, Payment Method, Location, Transaction Date]
Index: []

In [90]:
# check total missing value for transaction date by total data
naDate = (df['Transaction Date'].isna().sum()/df['Transaction Date'].count()*100)
print(naDate)

4.821802935010482

In [91]:
# the total missing value of Transaction date is 5% of the total number of data so  will decided to drop the data directly
df = df.dropna(subset=['Transaction Date'])
print(df.isna().sum())
print(df.shape)

Transaction ID      0
Item                0
Quantity            0
Price Per Unit      0
Total Spent         0
Payment Method      0
Location            0
Transaction Date    0
dtype: int64
(9540, 8)

In [92]:
# check duplicate data
print(df.duplicated().sum())

0

# **3. Feature Engineering** #

In [94]:
# Create new column for year,month, day and weekday
df["Day"] = df["Transaction Date"].dt.day
df["Month"] = df["Transaction Date"].dt.month_name()
df["Year"] = df["Transaction Date"].dt.year
df["Weekday"] = df["Transaction Date"].dt.day_name()

df

,Transaction ID,Item,Quantity,Price Per Unit,Total Spent,Payment Method,Location,Transaction Date,Day,Month,Year,Weekday
0,TXN_1961373,Coffee,2,2.0,4.0,Credit Card,Takeaway,2023-09-08,8,September,2023,Friday
1,TXN_4977031,Cake,4,3.0,12.0,Cash,In-store,2023-05-16,16,May,2023,Tuesday
2,TXN_4271903,Cookie,4,1.0,4.0,Credit Card,In-store,2023-07-19,19,July,2023,Wednesday
3,TXN_7034554,Salad,2,5.0,10.0,Digital Wallet,Takeaway,2023-04-27,27,April,2023,Thursday
4,TXN_3160411,Coffee,2,2.0,4.0,Digital Wallet,In-store,2023-06-11,11,June,2023,Sunday
...,...,...,...,...,...,...,...,...,...,...,...,...
9995,TXN_7672686,Coffee,2,2.0,4.0,Digital Wallet,Takeaway,2023-08-30,30,August,2023,Wednesday
9996,TXN_9659401,Juice,3,3.0,9.0,Digital Wallet,Takeaway,2023-06-02,2,June,2023,Friday
9997,TXN_5255387,Coffee,4,2.0,8.0,Digital Wallet,Takeaway,2023-03-02,2,March,2023,Thursday
9998,TXN_7695629,Cookie,3,1.0,3.0,Digital Wallet,Takeaway,2023-12-02,2,December,2023,Saturday
9999,TXN_6170729,Sandwich,3,4.0,12.0,Cash,In-store,2023-11-07,7,November,2023,Tuesday

# **4. Connect dataset to SQL for Data Analysis** #

In [96]:
import warnings
warnings.filterwarnings('ignore')

!pip install sqlalchemy
!pip install pymysql

from sqlalchemy import  create_engine

user = 'root'
password = 'password'
host = '127.0.0.1'
port = 3306
database = 'GeeksForGeeks'

engine = create_engine("mysql+pymysql://root:yklim121200@127.0.0.1:3306/cafe_sale")

conn = engine.connect()
df.to_sql('cafe',engine,index=False,if_exists='replace')
conn.close()

Requirement already satisfied: sqlalchemy in d:\anaconda\lib\site-packages (2.0.34)
Requirement already satisfied: typing-extensions>=4.6.0 in d:\anaconda\lib\site-packages (from sqlalchemy) (4.11.0)
Requirement already satisfied: greenlet!=0.4.17 in d:\anaconda\lib\site-packages (from sqlalchemy) (3.0.1)
Requirement already satisfied: pymysql in d:\anaconda\lib\site-packages (1.1.2)

# **5. Save latest cleaned dataset in csv file for data vizualization in Power BI**#

In [98]:
df.to_csv("Cleaned_cafeData.csv")